repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: end-of-file-fixer
      # - id: no-commit-to-branch   # to protect specific branches from direct checkins.
      #   args: [--branch, master, --branch, main]
      - id: pretty-format-json
        args: [--autofix]
