" Generated by vim-plug
" 日 10/17 10:47:34 2021
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['auto-pairs'].commit = '39f06b873a8449af8ff6a3eee716d3da14d63a76'
silent! let g:plugs['barbar.nvim'].commit = '6e638309efcad2f308eb9c5eaccf6f62b794bbab'
silent! let g:plugs['chadtree'].commit = '6946746b05d45080bb83362275b4762f47fd4691'
silent! let g:plugs['coc.nvim'].commit = '287c743c9f227fdf0e1db452bbb8ae3c5caffc36'
silent! let g:plugs['fzf'].commit = '5fc78e4584eface9f2055ee7c31c2ae8c5cedc87'
silent! let g:plugs['fzf.vim'].commit = '0452b71830b1a219b8cdc68141ee58ec288ea711'
silent! let g:plugs['gitsigns.nvim'].commit = 'ceb2dcb23f569ce337deb1b1ce7d4a51434cec32'
silent! let g:plugs['lualine.nvim'].commit = '9726824f1dcc8907632bc7c32f9882f26340f815'
silent! let g:plugs['markdown-preview.nvim'].commit = 'e5bfe9b89dc9c2fbd24ed0f0596c85fd0568b143'
silent! let g:plugs['md-img-paste.vim'].commit = 'c0aa411d9ebfeedff87b2177055c530246561dd8'
silent! let g:plugs['nvim-colorizer.lua'].commit = '36c610a9717cc9ec426a07c8e6bf3b3abcb139d6'
silent! let g:plugs['nvim-treesitter'].commit = '638891d401bb0269af404cce2f8367ac13053006'
silent! let g:plugs['nvim-ts-context-commentstring'].commit = 'a2283cfc9f4aa892349004153ab54dfe8911241c'
silent! let g:plugs['nvim-web-devicons'].commit = 'ee101462d127ed6a5561ce9ce92bfded87d7d478'
silent! let g:plugs['onedark.vim'].commit = 'a4dadcd2a37ea69624a808fd8fd47b540c797a45'
silent! let g:plugs['plenary.nvim'].commit = '80bb2b9bb74bdca38a46480b6f2e15af990406e4'
silent! let g:plugs['quick-scope'].commit = '892a2334be832e6834db68c2355e6f59dc6536bd'
silent! let g:plugs['rainbow_parentheses.vim'].commit = '27e7cd73fec9d1162169180399ff8ea9fa28b003'
silent! let g:plugs['rnvimr'].commit = 'ad2d155d7e1a633a597ed3b01e5a8eb084471620'
silent! let g:plugs['tmuxline.vim'].commit = '4119c553923212cc67f4e135e6f946dc3ec0a4d6'
silent! let g:plugs['vim-commentary'].commit = '627308e30639be3e2d5402808ce18690557e8292'
silent! let g:plugs['vim-fugitive'].commit = '2e66b3ad05d85f09d870f82671b8503cf8fa4297'
silent! let g:plugs['vim-indent-guides'].commit = '54d889a63716ee2f1818aa2ec5082db47147147b'
silent! let g:plugs['vim-pydocstring'].commit = 'f6e3c52bfaf4b4f76dab4d84e75b94199d5f3b9c'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-rooter'].commit = '0415be8b5989e56f6c9e382a04906b7f719cfb38'
silent! let g:plugs['vim-sneak'].commit = '95374ad3e4b5ef902854e8f4bcfa9a7a31a91d71'
silent! let g:plugs['vim-snippets'].commit = 'be519f70ab806c290a7b3d2e38fc22da07834052'
silent! let g:plugs['vim-startify'].commit = '81e36c352a8deea54df5ec1e2f4348685569bed2'
silent! let g:plugs['vim-surround'].commit = 'aeb933272e72617f7c4d35e1f003be16836b948d'
silent! let g:plugs['vim-textobj-entire'].commit = '64a856c9dff3425ed8a863b9ec0a21dbaee6fb3a'
silent! let g:plugs['vim-textobj-user'].commit = '41a675ddbeefd6a93664a4dc52f302fe3086a933'
silent! let g:plugs['vim-unimpaired'].commit = '39f195d7e66141d7f1fa683927547026501e9961'
silent! let g:plugs['vim-visual-star-search'].commit = '7c32edb9e3c85d473d9be4dec721a4c9d5d4d69c'
silent! let g:plugs['vim-which-key'].commit = '2c915b6de918c073fbd83809e51343651f00f9a8'

PlugUpdate!

